server:
  port: 8090
eureka: 
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/world?serverTimezone=PRC
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: after_route
        uri: http://www.163.com
        predicates:
        - After=2017-01-20T17:42:47.789-07:00[America/Denver]